OHBA-analysis/osl-ephys

osl/report/raw_report.py
osl/report/templates/fif_base.html.jinja2
osl/report/templates/fif_base_tabs.html.jinja2

Create a tab with the Bad ICA components. For each bad component, the component properties are plotted and the title indicates as what category the component was labeled

Add ICA tab to report

---

osl/preprocessing/batch.py

After running the preprocessing, add a copy of the config plus information about when the preprocessing was run to info['description'] of raw and epochs objects

append the config to info['description']

---

osl/preprocessing/batch.py
osl/report/raw_report.py
osl/report/templates/panel.html
osl/report/templates/raw_report.html

Set up the raw report to create flowchart figures of the preprocessing pipeline stored in raw.info['description']. It is not yet added to the html template

Report flowchart figures

---

osl/README.md
osl/preprocessing/README.md
osl/report/README.md
osl/report/raw_report.py
osl/rhino/README.md
osl/rhino/batch.py

Minor changes to out of date READMEs.

Updated READMEs.

---

examples/camcan/source_reconstruct.py
examples/oxford_covid/coregister_and_source_reconstruct.py
examples/oxford_covid/source_reconstruct.py
osl/source_recon/batch.py
osl/source_recon/beamforming.py
osl/source_recon/parcellation.py
osl/source_recon/rhino.py
osl/utils/logger.py

Cleaned up the logging during source reconstruction and fix bug in estimating the noise covariance matrix.

Source reconstruction improvements

---

examples/camcan/README.md
examples/oxford_covid/README.md
osl/preprocessing/mne_wrappers.py

This fixes https://github.com/OHBA-analysis/oslpy/issues/4.

High pass filter (1 Hz) before ICA

---

osl/preprocessing/batch.py
osl/tests/test_batch_preproc.py

This functionality was removed in ac532ffcb5f50fd9c1c20f23b4fabd847a99a893 and reintroduced here.

ENH: run_proc_chain can return dataset (default)

---

examples/mrc_meguk/notts/source_reconstruct.py
osl/report/src_report.py
osl/source_recon/batch.py
osl/source_recon/rhino/coreg.py
osl/source_recon/rhino/surfaces.py
osl/source_recon/wrappers.py

Closes: https://github.com/OHBA-analysis/oslpy/issues/62

Restructured the output files in source reconstruction.

---

examples/sign_flipping.py
osl/source_recon/sign_flipping.py

Changes:
- Fixed a minor bug in the sign flipping
- Added a standalone example script that can be used to sign flip data prepared in matlab.

Sign flipping

---

osl/preprocessing/osl_wrappers.py

add detection of zeroed out data by maxfilter (based on logfile)

---

osl/preprocessing/osl_wrappers.py
osl/report/raw_report.py
osl/report/templates/raw_panel.html

Added 
- ability to pass the alpha level to the bad segment detection
- extra bad channels hist plot to show before and after bad channel removal
- correction to ensure that bad channels hist plot does not include bad segments
- extra plot_channel_time_series plot to show before and after bad segment removal

Enhancements to preproc report

---

envs/bmrc.yml
envs/hbaws-no-display.yml
osl/report/src_report.py
osl/source_recon/batch.py
osl/source_recon/rhino/coreg.py
osl/source_recon/rhino/surfaces.py
osl/source_recon/wrappers.py

Closes https://github.com/OHBA-analysis/oslpy/issues/74 and https://github.com/OHBA-analysis/oslpy/issues/72.
Changes:
- Added features in the above issues.
- Updated conda environments to install open3d.

Source recon improvements

---

osl/preprocessing/batch.py
osl/source_recon/rhino/surfaces.py
osl/source_recon/sign_flipping.py
osl/source_recon/wrappers.py

Minor fixes related to source reconstruction.

Minor Fixes

---

osl/preprocessing/osl_wrappers.py

Wrong channels are labelled as bad in bad chan detection when bad channels already exist
Also added ability to pass in significance level to bad chan detection.

Fixed bug in badchannel detection

---

examples/notts_movie_opm/prepare_parcelts.py
examples/self_paced_fingertap/self_paced_fingertap.py
osl/source_recon/rhino/coreg.py

Fixed bug in coreg of OPM data
Also improved colors in coreg_display

Fixes to coreg of OPM data, also improved colors in coreg_display

---

examples/camcan/source_reconstruct.py
examples/oxford_covid/source_reconstruct.py
osl/preprocessing/batch.py
osl/utils/file_handling.py

Closes https://github.com/OHBA-analysis/oslpy/issues/69.

Each subject gets its own preproc output directory.

---

osl/preprocessing/plot_ica.py

I fixed a few issues that came up in the plotting function that appeared when scrolling past the number of ICA components (e.g. to the artefact channels), and when closing the figure.

Fix plot ica

---

osl/tests/test_00_package_canary.py
osl/utils/__init__.py
osl/utils/package.py
setup.py

Tweak package_data structure - lots of binary files aren't tracked by setup.py during packaging.

Update package data

---

osl/report/src_report.py
osl/source_recon/rhino/coreg.py

Fixed problems with coreg and coreg report when data has already been coregistered

Fixed problems with coreg and coreg report when already coregistered

---

examples/notts_movie_opm/prepare_parcel_ts.py
osl/report/src_report.py
osl/report/templates/src_summary_panel.html
osl/source_recon/parcellation/parcellation.py
osl/source_recon/rhino/coreg.py
osl/source_recon/rhino/utils.py
osl/source_recon/wrappers.py

Changes:
- Cleaned up the OPM example.
- Simplified the fix here: https://github.com/OHBA-analysis/osl/pull/131.
- Improved the system call function in RHINO.

Source reconstruction report fixes

---

CITATION.cff
osl/__init__.py
setup.py

v0.2.0 release.

---

envs/bmrc.yml

Updated to newer versions on BMRC.

Updated BMRC conda environment.

---

osl/source_recon/parcellation/parcellation.py

Changes:
- Added a function to calculate an adjacency matrix based on geodesic distance between parcel centroids.
- Cleaned up the parcellation module.

Parcellation spatial adjacency matrix

---

examples/mrc_meguk/notts/preproc_and_parcellate.py
examples/wakeman_henson/recon_and_parcellate.py
osl/source_recon/parcellation/parcellation.py
osl/source_recon/rhino/coreg.py
osl/source_recon/wrappers.py

Minor changes to some examples and documentation
Exposed option to set gridstep size to forward_model batch call

Minor improvements for recon OSL workshop

---

examples/wakeman_henson/first_level_glm.py
examples/wakeman_henson/group_level_glm.py
examples/wakeman_henson/plot_group_parcel_stats.py
examples/wakeman_henson/recon_and_parcellate.py
osl/source_recon/parcellation/parcellation.py

Changes to wakeman henson processing
Added temporal res info to niftiis output from parcellations

Changes to wakeman henson processing

---

osl/__init__.py
osl/glm/__init__.py
osl/glm/glm_epochs.py
osl/glm/glm_spectrum.py
requirements.txt
setup.py

Classes and functions for GLM-Spectra and GLM-Epochs analysis
Work in progress for the moment - Epochs needs some finishing...

GLM Module

---

osl/glm/glm_base.py
osl/glm/glm_epochs.py
osl/glm/glm_spectrum.py
osl/utils/study.py

Work-in-progress for gradual updates and fixes for glm module

GLM module updates

---

osl/report/raw_report.py

Fixed bug in bad segments summary plot when there are no bad segs

Fixed bug in bad segments summary plot when there are no bad segs

---

osl/__init__.py
setup.py

bump to v0.5.dev0

---

osl/source_recon/parcellation/parcellation.py

Bug in creating MNE epochs object from parcellated data

---

osl/source_recon/rhino/surfaces.py
osl/source_recon/rhino/utils.py
osl/source_recon/sign_flipping.py

Closes https://github.com/OHBA-analysis/osl/issues/262.
Changes:
- Removed pre-specified progress bar size in sign flipping (now uses the width of the screen).
- Added a warning for `nan`s being present in a structural MRI file.

Improvements

---

envs/windows.yml
osl/report/preproc_report.py
osl/report/src_report.py
osl/source_recon/rhino/utils.py
osl/source_recon/wrappers.py

Revert "Changed reference brain + beamforming regularisation"

---

examples/spectrum_analysis_walkthrough.py
osl/glm/glm_spectrum.py
osl/preprocessing/batch.py
osl/tests/test_glm.py
osl/utils/simulate.py

Merging changes from a few branches of GLM updates

GLM Spectrum Update

---

osl/report/preproc_report.py
osl/report/src_report.py
osl/source_recon/beamforming.py
osl/source_recon/rhino/coreg.py
osl/source_recon/rhino/forward_model.py
osl/utils/file_handling.py
osl/utils/opm.py

There has been a re-org in MNE which shifts around a bunch of imports.
Changes here should be valid for current and future MNE and removes a load of depreciation warnings.

Future proofing imports

---

requirements.txt

We use a function in OSL that was introduced in SAILS 1.6. This PR updates the requirements to use sails>=1.6.0.

Updated SAILS requirement.

---

osl/source_recon/beamforming.py

Fix minor bug in beamforming.py

Fix bug in beamforming.py

---

osl/source_recon/parcellation/parcellation.py

This PR demeans the voxel time series when parcellating them into parcel time series.

Demean the voxel time series when parcellating.

---

osl/preprocessing/batch.py

Enable reading .sqd/.con files

---

examples/fix_smri_files.py
osl/source_recon/beamforming.py

Changes:
- Improved the function used to get leadfields.
- Fixed typo in examples.

Functionality to get leadfields

---

doc/source/api.rst
osl/source_recon/beamforming.py
osl/source_recon/parcellation/parcellation.py
osl/source_recon/wrappers.py

Changes needed to create simulation examples for source reconstruction:
https://github.com/OHBA-analysis/meg-simulation

Source reconstruction simulation example

---

doc/source/install.rst
envs/README.md
envs/linux-full-with-spyder.yml
envs/linux-full.yml
envs/linux-with-spyder.yml
examples/camcan/2_coregister.py
examples/oxford/automated_ica_pipeline/3_coregister.py
examples/oxford/manual_ica_pipeline/4_coregister.py
examples/oxford/no_viz_pipeline/do_rhino.py
examples/oxford/projects/int_ext/5_source_reconstruct.py
examples/oxford/projects/pd_gripper/3_coregister.py
examples/oxford/ssp_pipeline/4_coregister.py
examples/parallelisation/parallel_source_reconstruct.py
examples/parallelisation/serial_source_reconstruct.py
examples/wakeman_henson/2023_workshop/2_recon_and_parcellate.py
examples/wakeman_henson/full_preproc/2_source_reconstruct.py
osl/preprocessing/batch.py
osl/preprocessing/mne_wrappers.py
osl/source_recon/batch.py
osl/source_recon/rhino/polhemus.py
osl/source_recon/wrappers.py

Changes:
- Updated installation instructions.
- Option to specify report/log directories in source reconstruction.
- Include function to clean up headshape points as a wrapper.
- Option to pass `'standard'` for structural MRI.
- Option to read BDF (EEG) files.
- Updated examples.

More features and enhancements

---

doc/source/conf.py
envs/bmrc.yml
envs/linux-full-with-spyder.yml
envs/linux-full.yml
envs/mac-full.yml

Changes:
- Updated environments/instructions to reflect the new TensorFlow requirements of the latest osl-dynamics.

Updated TensorFlow Requirements in OSL-Dynamics

---

osl/source_recon/rhino/surfaces.py

Added a message to inform the user when the qform transformation is being used (this is non-standard so would be useful to have a message).

Using qform message

---

osl/preprocessing/mne_wrappers.py

Previously ICA didn't have as many options as MNE provides. Add these manually.

Add ica input args

---

osl/report/preproc_report.py
osl/report/src_report.py
osl/report/templates/raw_subject_panel.html
osl/report/templates/raw_summary_panel.html
osl/report/templates/src_subject_panel.html
osl/report/templates/src_summary_panel.html
osl/report/templates/summary_report.html

Summary of changes:
- Add in `Logs` tab in the subject reports (if they are found)
- Add in `Maxfilter` tab in the subject reports (if maxfilter logs are found)
- Add summary metrics to the preproc summary report, in an interactive table (e.g., number of IC's removed, % of data removed)
- Replace clunky tables/figures with interactive tables
- bugfixes

ENH: improvement in raw and src reports. 

---

osl/preprocessing/batch.py

Closes https://github.com/OHBA-analysis/osl/issues/306.

Fixed bug with yaml loader.

---

osl/preprocessing/batch.py
osl/preprocessing/ica_label.py
osl/report/preproc_report.py
osl/report/src_report.py
osl/report/templates/raw_summary_panel.html
osl/report/templates/src_summary_panel.html
osl/source_recon/batch.py
setup.py

Changes based on #310 :
- Save "extra_funcs" as text in the report `data.pkl`
- Index tables start from 1
- summary reports contain batch log, and error logs tab
- improvements in the sign flipping tab of the summary source report
- I also implemented a command line ICA labelling tool - with auto update of the report (tested on Mac M1 and hbaws)

various report improvements (#310)

---

osl/maxfilter/maxfilter.py

The calibration files were moved on hbaws, we update them here.

Updated maxfilter calibration/cross talk file paths.

---

osl/preprocessing/ica_label.py

Improve the documentation of the osl_ica_label command line function

Update osl_ica_label doc

---

doc/source/conf.py
osl/__init__.py
setup.py

Released and updated version numbers.

Released v0.9.0

---

osl/preprocessing/batch.py
osl/preprocessing/ica_label.py
osl/preprocessing/plot_ica.py
setup.py

changes:
- fixed batch processing suffix (#336 )
- Added log update to `osl_ica_label`
- Added `osl_ica_apply` command line function

preproc batch and ICA label improvements

---

osl/source_recon/beamforming.py
osl/source_recon/rhino/coreg.py
osl/source_recon/wrappers.py

Change:
- Fixes and extra features to source reconstruct mne.Epochs objects.

Features for source reconstructing epoched data

---

osl/preprocessing/batch.py
osl/report/preproc_report.py
osl/report/templates/raw_summary_panel.html
osl/source_recon/batch.py
osl/utils/misc.py

Summary of changes:
- add util function for setting global random seed (python & numpy)
- enable setting random seed in `chain` and `batch` functions
- by default initialize a global random seed in `chain` and `batch` functions
- A few small preproc report improvements

Randomseed

---

osl/glm/glm_base.py
osl/glm/glm_epochs.py
osl/glm/glm_spectrum.py
osl/preprocessing/batch.py

Add the ability to pass `tmin`, `tmax`, `fmin`, `fmax`, and `picks` to a permutation class. This will only make a selection of the data for permutations and for determining significance, not for plotting.

Glm epochs

---

osl/source_recon/batch.py

This PR fixes a typo in run_src_batch

fix typo in run_src_batch

---

osl_ephys/preprocessing/batch.py

Minor correction to the report/log directory using `run_proc_chain`.

Fix report/log directory path.

---

osl_ephys/source_recon/rhino/coreg.py
osl_ephys/source_recon/rhino/surfaces.py
osl_ephys/source_recon/rhino/utils.py
osl_ephys/source_recon/wrappers.py

Closes https://github.com/OHBA-analysis/osl-ephys/issues/347.
Changes:
- Reformatted docstrings.
- Fixed typos/small bugs.
- Added `cleanup_files` arguments for `compute_surfaces` wrapper.

Fixes and Improvements for RHINO

---

osl_ephys/preprocessing/batch.py
osl_ephys/preprocessing/osl_wrappers.py
osl_ephys/report/preproc_report.py

It's now possible to run subject and group level GLMs (including permutations) using the preproc batch config.

Add GLM wrappers to preprocessing

---

doc/source/tutorials/glm_sensor.py
doc/source/tutorials/glm_sensor_solution.py
doc/source/tutorials/glm_simulation.py
doc/source/tutorials/glm_simulation_solution.py
envs/bmrc.yml
envs/hbaws.yml
envs/linux-full-with-spyder.yml
envs/linux-full.yml
envs/linux-with-spyder.yml
envs/linux.yml
envs/mac-full.yml
envs/mac-with-spyder.yml
envs/mac.yml
osl_ephys/glm/glm_base.py
osl_ephys/glm/glm_spectrum.py

Not working yet - don't merge!
Will need a new release of glmtools.

AQ Workshop Changes
