OHBA-analysis/osl-ephys

- osl/report/raw_report.py
Since `nk.ecg_plot` doesn't return a figure, get the figure explicitly after plotting.
> get current figure after ecg_plot

- osl/report/raw_report.py
OSL preprocessed raw files have the extension `preproc_raw.fif` instead of `raw.fif`. Remove the `preproc_` when looking for accompanying ICA file.
> Fix finding ICA files based on raw filename

- doc/source/tutorials/osl_tutorial_preproc.py
Replace `osl.preprocessing.batch.detect_badsegments` (which doesn't exist) with `osl.preprocessing.osl_wrappers.detect_badsegments` (which does).
> bug:simulation tutorial

- osl/rhino/rhino_utils.py
Rhino uses numba: https://github.com/OHBA-analysis/oslpy/blob/main/osl/rhino/rhino_utils.py. This causes a large number of logger messages to be printed to screen when importing osl (on the BMRC server and locally on my mac). Here, we change the level of the logger to only print messages that are at the level of warnings or above.
> Suppress numba warning when importing osl.

- examples/mrc_meguk/notts/fix_smri_files.py
- examples/mrc_meguk/notts/preprocess.py
- examples/mrc_meguk/notts/sign_flip.py
- examples/mrc_meguk/notts/source_reconstruct.py
- osl/sign_flipping/__init__.py
- osl/sign_flipping/data_preparation.py
- osl/sign_flipping/sign_flipping.py
- osl/sign_flipping/wrappers.py
- osl/source_recon/batch.py
- osl/source_recon/beamforming.py
- osl/source_recon/wrappers.py
Changes:
- Added a subpackage for sign flipping.
- Worked on the preprocessing and source reconstruction example that uses the Nottingham data in the UK MEG partnership dataset:
- Training an HMM (using MATLAB HMM-MAR) on amplitude envelope (source reconstructed) data preprocessed with oslpy gives a reasonable fit, both with and without learning a mean.
- Training an HMM (using MATLAB HMM-MAR) on time-delay embedded/PCA (source reconstructed) data preprocessed with oslpy gives reasonable power and coherence maps (trained with zero mean).
- Minor improvements to the source reconstruction.
> Sign flipping + Nottingham preprocessing and source reconstruction working

- doc/source/tutorials/osl_tutorial_preproc_wakehen.py
- examples/self_paced_fingertap/self_paced_fingertap.py
- examples/wakeman_henson/wakeman_henson.py
- osl/preprocessing/README.md
- osl/preprocessing/batch.py
- osl/report/raw_report.py
- osl/tests/test_batch_preproc.py
Fixes: https://github.com/OHBA-analysis/oslpy/issues/51.
Swapped the order of the input file and config in run_proc_chain so that all batch processing functions have a consistent argument ordering.
> Changed order of run_proc_chain arguments for consistency.

- osl/preprocessing/batch.py
gen_report was always set to True, even when the user passes False.
I fixed this, so this should now behave as originally intended, i.e. set it True, if the user doesn't specify the gen_report argument, otherwise keep the user-specified argument.
> gen_report is now overridable by user

- osl/maxfilter/maxfilter.py
Fixes #27 
in `run_multistage_maxfilter`, the [autobad extension is added to the fif file](https://github.com/OHBA-analysis/oslpy/blob/main/osl/maxfilter/maxfilter.py#L320), and then `_autobad` is given as a logfile_tag in the call to `run_maxfilter`. Because the filename of the log and error log is based on the fif file already, `autobad` is added twice. This also holds for the `tsss` and `trans` extensions.
The same is true for `run_cbu_3stage_maxfilter`.
I removed the logfile_tags in these functions to resolve this issue.
> FIX: fix log filenames in multistage and 3stage

- osl/preprocessing/batch.py
- osl/report/raw_report.py
Hi,
I'm proposing 2 bug fixes.
1. html report in run_proc_chain:
It seems that a gen_html_page call was missing after gen_html_data in run_proc_chain. This means that the HTML page for the report was not generated. I verified and with the suggested modification it gets generated.
2. Digitisation in raw_report:
I think the report generation assumed there is digitisation stuff available in raw.info['dig']. But this is not the case for EEG or OPM data for example. So all I did, was to check whether raw.info['dig'] is None before accessing it in the 2 places the report generation accesses it. I checked and the report generation now works for EEG data without digitisation info.
Cheers,
Richard
> fixed digitisation in report and html page issue

- osl/preprocessing/batch.py
- osl/preprocessing/mne_wrappers.py
- osl/preprocessing/osl_wrappers.py
- requirements.txt
**Description**:
_Bug:_ `ica_manualreject` currently fails as it is an OSL wrapper in `mne_wrappers.py` and batch.py only looks for OSL->OSL correspondence. Moved to `osl_wrappers.py`.
_Feature:_ support using EEGLAB .set files. This simply adds MNE's `read_raw_eeglab` to importing. However, as some EEGLAB versions save using .mat version 7.3+ (not supported by `scipy.io.loadmat`), MNE requires optional import of pyreadmat to be in place. This was added to requirements.
> Bug fix: manual_ICA OSL wrapper in MNE wrapper file; Feature: support importing EEGLAB .set files

- osl/report/raw_report.py
Hi,
There was an inconvenience in the plot_bad_ica function because it assume ica.labels_ would not be empty, and would throw an error otherwise. I just included a check for this, and if ica.labels_ is empty, it gets initialized with empty strings, so the subsequent code doesn't throw errors.
Cheers,
Richard
> fixed ica labels empty issue

- examples/self_paced_fingertap/self_paced_fingertap.py
- osl/source_recon/beamforming.py
- osl/source_recon/rhino/coreg.py
- osl/source_recon/rhino/forward_model.py
- osl/source_recon/rhino/surfaces.py
- osl/source_recon/rhino/utils.py
- osl/source_recon/wrappers.py
Added allow_smri_scaling option to coreg, which makes the sMRI scale to a size to match the polhemus fids.
Forward modelling and recon is carried out based on the scaled MRI.
Refactored coreg and compute_surfaces so that files are more sensibly allocated to their corresponding dirs
- freesurfer meshes now in coreg dir
- unscaled files in surfaces fir
- scaled files in coreg
> add option to scale sMRI to match size dictated by polhemus fids

- osl/preprocessing/mne_wrappers.py
When logging the number of EOG and ECG ICs, `len(dataset["ica"].exclude)` is printed in both cases. However, the excluded IC indices here are cumulative. That is, when the number of ECG ICs is reported, the number of both EOG and ECG components is being printed out. This commit is to fix this error.
> Fix: logger errors in reporting the number of ICA components

- examples/lemon/source_reconstruct.py
- examples/mrc_meguk/notts/source_reconstruct.py
- examples/notts_movie_opm/prepare_parcel_ts.py
- examples/oxford/covid/preprocess.py
- examples/oxford/covid/source_reconstruct.py
- examples/oxford/dg_int_ext/5_source_reconstruct.py
- examples/parallelisation/parallel_source_reconstruct.py
- examples/parallelisation/serial_source_reconstruct.py
- examples/wakeman_henson/recon_and_parcellate.py
- osl/preprocessing/batch.py
- osl/report/src_report.py
- osl/source_recon/batch.py
- osl/source_recon/rhino/coreg.py
- osl/source_recon/rhino/surfaces.py
- osl/source_recon/wrappers.py
Closes: https://github.com/OHBA-analysis/osl/issues/148, https://github.com/OHBA-analysis/osl/issues/149.
Changes:
- More consistent naming convention for source reconstruction wrappers:
- coregister -> compute_surfaces_coregister_and_forward_model
- coreg -> coregister.
- Fixed typo in error message.
- Raise a value error if fif files or output file paths contain spaces.
- Only generate a source reconstruction report if we successfully processed a subject.
Note, this is an API change, will break some source reconstruction scripts.
> More consistent naming convention for source reconstruction wrappers

- osl/report/templates/src_subject_panel.html
- osl/report/templates/src_summary_panel.html
- osl/source_recon/wrappers.py
Changes:
- Fixed bug when generating the coreg section of the report introduced in https://github.com/OHBA-analysis/osl/pull/153.
- Made the source reconstruction wrappers more consistent with the low-level functions.
> Coregististration Report Bugs

- README.md
- envs/bmrc.yml
- envs/hbaws.yml
- envs/m1_mac.yml
- envs/osl-workshop-23.yml
- osl/source_recon/rhino/utils.py
- setup.py
Closes https://github.com/OHBA-analysis/osl/issues/146.
Changes:
- For some reason the `coreg.html` plots of the coregistration have broken, previously generated `coreg.html` files and new ones no longer open in any web browser. This might be due to updated to the web browsers. Switching the backend from `threejs` to `panel` has resolved this.
- `threejs` was removed from the dependencies and `panel` was added.
> Switch coreg html backend to panel (from threejs)

- osl/source_recon/beamforming.py
Changes:
- `reject_by_annotation` was removed from the beamforming because we decided to retain bad segments in the parcellated data. However, this argument is used in the tutorials so I reintroduce this argument here.
> Added option to reject bad segments when calculating voxel data.

- osl/source_recon/beamforming.py
- osl/source_recon/parcellation/parcellation.py
- osl/source_recon/sign_flipping.py
- osl/source_recon/wrappers.py
- osl/utils/logger.py
Changes:
- We should not include bad segments in the voxel time series at the parcellation step. The current code reproduces the parcel data we generated in the previous code when we were saving as npy files.
- Modified the interface for saving extra channels to the `parc-raw.fif` file.
- Updated sign flipping to work on channels named `parcel_..`, this is useful in case we have other channels of type misc in parc-raw.fif.
- Added a warning if no stim channel was added to `parc-raw.fif`
> Parcellation Updates

- envs/osl-workshop-23.yml
Changes:
- Updated osl to 0.3.0.
- Updated osl-dynamics to 1.2.1.
- Removed pre-commit (no longer a dependency of osl-dynamics).
- Added osfclient to help workshop attendees download data directly from OSF.
> Final OSL Workshop 23 Conda Env

- osl/preprocessing/osl_wrappers.py
- osl/report/raw_report.py
When bad segment detection is done following previous bad seg detection, it starts again from scratch and does not take into account any previously marked bad segments
> Fixed bug in bad segments

- osl/source_recon/rhino/coreg.py
- osl/source_recon/rhino/surfaces.py
- osl/source_recon/wrappers.py
Added new option to compute_surfaces so that the first step can be turned off.
New option is:
do_mri2mniaxes_xform : bool
Specifies whether to do step 1), i.e. transform sMRI to be
aligned with the MNI axes. Sometimes needed when the sMRI goes out
of the MNI FOV after step 1).
Note that the default behaviour for compute_surfaces is as before, i.e. to do step 1 by virtue of do_mri2mniaxes_xform having a default value of True
> Added option to omit step 1 in rhino.surfaces.compute_surfaces

- osl/source_recon/parcellation/parcellation.py
Sometimes `raw.time_as_index` miss assigns the index that corresponds to a particular time point. For example, using
```
times = [0, 0.1, 0.2, 0.3, 0.4, …]
indices = raw.time_as_index(times)
```
You might get something like
```
indices = [0, 1, 1, 3, 4, …]
```
Rather than what you really want, which is `indices = [0, 1, 2, 3, 4, …]`.
We resolve this issue in this PR by passing `raw.time_as_index(times, use_rounding=True)`.
> Source Reconstruction Fixes

- osl/source_recon/rhino/coreg.py
- osl/source_recon/wrappers.py
`n_init=30` often causes over rotation of the head when matching to the headshape points. On multiple datasets, using `n_init=1` as the default gives (much) better coreg.
Note, it's straightforward for the user to specify a higher `n_init` by passing this arguments to `rhino.coreg.coreg` or in the source reconstruction config.
> Changed coregistration defaults (n_init)

- osl/preprocessing/batch.py
- osl/report/raw_report.py
Fixes #218 
Instead of assuming that all preprocessed MEG files are called `..._preproc_raw.fif`, we enable user input by specifying `ftype` in functions `run_proc_chain`, `run_proc_batch`, `write_dateset`, `read_dataset`, and `gen_report_from_fif`. If this is not specified, it will try using `preproc_raw` anyway, and otherwise guess whatever comes in between the last `_` and `.fif`.
> [Fix #218] enable user specification of file extension

- examples/oxford/ssp_pipeline/3_ssp_denoise.py
Fixed a bug where we didn't save the cleaned data in an example script.
> Fix: save the SSP cleaned data (rather than the original data).

- osl/maxfilter/maxfilter.py
Changed naming of trans files.
Fixes #247 and #210
> Fix transsss filename issue in maxfilter

- osl/utils/__init__.py
- osl/utils/run_func.py
- setup.py
This is a utility function addition to run any osl function (with limitations) from the terminal command line, i.e.,  `osl_func function_name arg1 arg2`. 
Example: 
`osl_func osl.source_recon.rhino.polhemus.delete_headshape_points None None polhemus_headshape.txt` will iteratively load the (sub-) module until it reaches the function, and then run the function with the function arguments. This example will run  `osl.source_recon.rhino.polhemus.delete_headshape_points(recon_dir=None, subject=None, polhemus_headshape_file='polhemus_headshape.txt')`.
This is especially useful for interactive functions, which often don't work very well in Jupyter Notebook. Because I expect that this is an issue that many people will face, I thought this would be useful (so users don't have to make separate …
> osl_func utility: run any function from the command line

- osl/preprocessing/batch.py
- osl/report/preproc_report.py
- osl/report/src_report.py
- osl/report/templates/raw_subject_panel.html
- osl/report/templates/raw_summary_panel.html
- osl/report/templates/src_summary_panel.html
- osl/source_recon/batch.py
Summary of changes:
- in `run_proc_chain`, if extra_funcs is given, append the code of each function to `raw.info['description']` (appended after the config text)
- print the extra_funcs code to a scroll box in the preproc and source summary report, underneath the config (see below).
- in preproc_report, replace the legacy `raw.plot_psd()` with `raw.compute_psd().plot()`
> Improve report

- envs/windows.yml
- osl/report/preproc_report.py
- osl/report/src_report.py
- osl/source_recon/rhino/utils.py
- osl/source_recon/wrappers.py
Closes https://github.com/OHBA-analysis/osl/issues/269.
Changes:
- Use `MNI152_T1_1mm.nii.gz` instead of `MNI152_T1_1mm_brain.nii.gz` for the reference brain.
- Option to pass the regularisation for the beamforming filter in the wrappers.
> Changed reference brain + beamforming regularisation

- osl/preprocessing/osl_wrappers.py
Fixed missing variable bug when `mode='maxfilter'` is used in the OSL bad segment detection.
> Bug in bad segment detection

- examples/misc/fix_smri_files.py
- osl/source_recon/rhino/coreg.py
- osl/source_recon/rhino/forward_model.py
- osl/source_recon/rhino/polhemus.py
- osl/source_recon/rhino/surfaces.py
- osl/source_recon/rhino/utils.py
- osl/source_recon/wrappers.py
Changes:
- Added missing imports / removed unused imports.
- Updated the example script to fix structural MRIs.
- Added option to use qform instead of the sform.
> Option to use qform in surface extraction + minor fixes

- .github/workflows/osl-cicd-actions.yml
Git workflow used python 3.10, which caused an issue with the tests. Now match the git workflow to the recommended version: 3.8.16.
> Fixed Tests

- envs/mac-full.yml
- envs/mac-with-spyder.yml
- envs/mac.yml
Changes:
- `envs/mac.yml` didn't work with M1 chips (due to `pyqt` version not being available).
- This has been fixed.
- Tested with M1 and M2 chips.
-  New separate Mac environment with spyder.
> Updated Mac Installation

- osl/maxfilter/maxfilter.py
Allow `movecompinter` to be overwritten by user input. This is necessary when there are not enough usable HPI coils
> Update cbu3_stage maxfilter

- doc/source/conf.py
- envs/linux-full-with-spyder.yml
- envs/linux-full.yml
- envs/linux-with-spyder.yml
- envs/linux.yml
- envs/mac-full.yml
- envs/mac-with-spyder.yml
- envs/mac.yml
- envs/osl-workshop-23.yml
- release_notes.md
Issues:
- The readthedocs website was showing the incorrect version, this is because the source code for the documentation was not updated.
- The installation instructions would install an older release of OSL (due to dependency version issues).
Changes:
- We update the version in the docs.
- We added the file to the release notes to avoid this occurring again.
- Fixed the conda environemnts to make sure the latest OSL is installed when someone follows the official instructions.
> Installation + Release Notes

- osl/preprocessing/ica_label.py
Fixed a bug in finding how many ecg/eog components were rejected.
> fix ica_label.py report

- setup.py
Closes https://github.com/OHBA-analysis/osl/issues/329.
Previously the README.md files weren't included in the PyPI package. This caused an issue with installing the package via `pip` (where `osl` could not be imported). This PR resolve the issue.
> Include READMEs in PyPI package.

- osl/glm/glm_epochs.py
- osl/preprocessing/batch.py
- osl/preprocessing/osl_wrappers.py
- osl/utils/study.py
changes:
- implemented group processing in `osl.preproc.run_proc_batch`
- add `read_dataset` osl wrapper
- add `skip_save` argument to `run_proc_chain/batch` and `write_dataset` 
- added log statements when saving data in `write_dataset`
- added `Study.refresh()` function
- added `save_pkl` for `glm_epochs`
> Batch improvements

- osl_ephys/source_recon/rhino/utils.py
Util function to save the polhemus information from a raw MNE object to the specified coreg directory.
Nasion, LPA, RPA and headshape are exported as .txt (3xN)
> add save_polhemus_fif

- osl_ephys/source_recon/beamforming.py
Changes:
- Added a function to extract LCMV beamformer weights.
- Simplified the function to get leadfields.
- Improved docs for these functions.
Tested the beamforming projection with:
```
import mne
import numpy as np
from osl_ephys.source_recon import beamforming
subjects_dir = "data/raw/src"
subject = "sub-CC320608_task-rest"
preproc_file = "data/raw/preproc/mf2pt2_sub-CC320608_ses-rest_task-rest_meg/mf2pt2_sub-CC320608_ses-rest_task-rest_meg_preproc_raw.fif"
raw = mne.io.read_raw_fif(preproc_file, preload=True)
raw = raw.filter(l_freq=1, h_freq=45, method="iir", iir_params={"order": 5, "ftype": "butter"})
sensor_data = raw.get_data(picks="meg", reject_by_annotation="omit")
sensor_cov = np.cov(sensor_data)
voxel_data, _ = beamforming.voxel_timeseries(
subjects_dir=subjects_dir, …
```
> Improved functions to get leadfields and LCMV weights

- osl_ephys/source_recon/rhino/coreg.py
To help the user see the headshape points in situations with lots of points (aka from new OHBA OPM lab)
> change size of headshape points based on their number in coreg display

- examples/elekta/5_sign_flip.py
- osl_ephys/preprocessing/batch.py
- osl_ephys/source_recon/batch.py
- osl_ephys/source_recon/wrappers.py
- osl_ephys/utils/logger.py
I think since the package renaming (osl -> osl-ephs) the logging was broken. This is now fixed.
The `osl_batch.log` has been split into two different logs for the preprocessing (`batch_preproc.log`) and source recon (`batch_src.log`).
> Fixed logging

- requirements.txt
This fixes "Dask Vulnerable to Command Injection" (https://github.com/advisories/GHSA-xqgj-r6xv-9cw4)
> dask upgrade requirements

- osl_ephys/report/src_report.py
Closes: https://github.com/OHBA-analysis/osl-ephys/issues/390
There as a bug detecting when a source reconstruction run failed. The code tried to make a html report page when it shouldn't. This PR resolves this.
> Fix: don't generate a source reconstruction report page for failed runs

- osl_ephys/source_recon/parcellation.py
- osl_ephys/source_recon/wrappers.py
Next to the option for symmetric leakage correction of parcel time series, it is now possible to regress out neighbouring parcel's time series from each parcel, based on an adjacency matrix (determined through the distance between parcel centers)
> feat: local parcel orthogonalisation

- osl_ephys/source_recon/parcellation.py
We use scipy's `welch` function to plot the PSD of the parcellated data. The default parameters of this function raise an error if we source reconstruct 100 Hz data. This PR resolves this.
> Fixed bug plotting parcellated data PSD.

- osl_ephys/preprocessing/ica_label.py
- osl_ephys/preprocessing/mne_wrappers.py
- osl_ephys/preprocessing/plot_ica.py
- osl_ephys/report/preproc_report.py
Fixes ica_label, and added an mne wrapper to preprocessing module for interpolating bad channels (with reset_bads=False by default - needed to keep track of bad channels)
> Preprocessing fixes

- osl_ephys/preprocessing/batch.py
Fixing a missing variable in the call to `write_dataset`
> Add ftype parameter to write_dataset function
